definitions:
  models.Product:
    properties:
      createAt:
        type: string
      id:
        type: integer
      name:
        type: string
      price:
        type: number
      quantity:
        type: integer
      sells:
        items:
          $ref: '#/definitions/models.Sell'
        type: array
      updateAt:
        type: string
    type: object
  models.Sell:
    properties:
      createAt:
        type: string
      id:
        type: integer
      product:
        $ref: '#/definitions/models.Product'
      quantity:
        type: integer
    type: object
  product.ProductCreationRequest:
    properties:
      name:
        type: string
      price:
        type: number
      quantity:
        type: integer
    required:
    - name
    - price
    - quantity
    type: object
  product.ProductUpdateRequest:
    properties:
      name:
        type: string
      price:
        type: number
      quantity:
        type: integer
    type: object
info:
  contact: {}
paths:
  /products:
    get:
      consumes:
      - application/json
      description: Get all products
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Product'
            type: array
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get all products
      tags:
      - products
    post:
      consumes:
      - application/json
      description: Create a product
      parameters:
      - description: Product Creation Request
        in: body
        name: productCreationRequest
        required: true
        schema:
          $ref: '#/definitions/product.ProductCreationRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Product'
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Create a product
      tags:
      - products
  /products/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a product
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Delete a product
      tags:
      - products
    get:
      consumes:
      - application/json
      description: Get a product by ID
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Product'
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
      summary: Get a product by ID
      tags:
      - products
    put:
      consumes:
      - application/json
      description: Update a product
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      - description: Product Update Request
        in: body
        name: productUpdateRequest
        required: true
        schema:
          $ref: '#/definitions/product.ProductUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Product'
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Update a product
      tags:
      - products
  /products/{id}/qr:
    get:
      consumes:
      - application/json
      description: Get a product sells QR code
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - image/png
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Get a product sells QR code
      tags:
      - products
  /sells:
    get:
      consumes:
      - application/json
      description: Create a sell
      parameters:
      - description: Product ID
        in: query
        name: productId
        required: true
        type: integer
      - description: Quantity
        in: query
        name: quantity
        type: integer
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Sell'
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Create a sell
      tags:
      - sells
  /sells/{productId}:
    get:
      consumes:
      - application/json
      description: Get sells by product ID
      parameters:
      - description: Product ID
        in: path
        name: productId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Sell'
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Get sells by product ID
      tags:
      - sells
swagger: "2.0"
